# Numpy Review Problem Set

In [2]:
import numpy as np

#### Create an all zero numpy array of size 1000

In [4]:
# write code here
a = np.zeros(1000)

#### Create a numpy array from all digits between [0,1000) that are divisible by five

In [7]:
b = np.arange(0, 1000, 5)

#### Assign a 1 to every element divisible by 5 in the all zero array

In [10]:
# write code here
boo = (a % 5 == 0)
a[boo] = 1

#### Below is the grades for 6 students, convert to a numpy array

In [11]:
grades = [90, 94, 88, 80, 78, 85]
g = np.array(grades)

array([90, 94, 88, 80, 78, 85])

#### Scale every grade below 90 up by 2 points

In [14]:
boo_2 = (g < 90)
g[boo_2] += 2
g

array([90, 94, 90, 82, 80, 87])

#### Create a 10 by 10 matrix with 1 on the border 0 within the border

In [16]:
array_2 = np.ones((10, 10))
array_2[1:-1, 1:-1] = 0


## Challenge Problems

#### Create an 10 by 10 checkerboard matrix in three lines of code.
Below is an example of a 3 by 3 checkerboard matrix

In [ ]:
# [0 1 0]
# [1 0 1]
# [0 1 0]

In [27]:
z = np.zeros((10, 10))
z[1:10:2, 0:10:2] = 1
z[0:10:2, 1:10:2] = 1


#### Assume that you have an MxM array, a, and a number, n (where n < M). Using array attributes and slicing, print out the nxn subarray at the center of a (example below for n=3, M=5   -- you may assume that n is odd and that a has an odd number of rows and columns) 

In [ ]:
#
# 0 0 0 0 0
# 0 X X X 0      X X X
# 0 X X X 0 ---> X X X
# 0 X X X 0      X X X
# 0 0 0 0 0

In [33]:
def inputfun(a, M, n):
    subarray = a[(M-n-1):-(M-n-1), (M-n-1):-(M-n-1)]
    print(subarray)

M = np.ones((5, 5))
inputfun(M, 5, 3)

"""
M = 5
n = 3
a = np.arange(25).reshape((5,5))
print(a)

start = (M-n)/2
a[start:-start, start:-start]


[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
